#App Settings
#Wed May 20 17:18:39 JST 2026
fileExplorerBookmarks=/data/local/tmp,/data/local/tests
fileExplorerSplitPercent=0.471543
kmarks=/data/local/tmp,/data/local/tests
logcatBufferSize=100000
logcatPastMinutes=10
mcpServerHost=0.0.0.0
useMcpFallback=true
