name: Build Desktop Apps

# 手動実行、または「v」から始まるタグをプッシュした時に起動
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      # Windows、Linux、Macの3環境で並列ビルド
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build Native Distributable
        shell: bash
        # JPackageを使って、Java内包型のネイティブアプリを生成
        run: ./gradlew :composeApp:createReleaseDistributable

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TestbedCore-${{ matrix.os }}
          # OSごとの出力パスのブレを吸収するため、ワイルドカードでappディレクトリ配下をすべて取得
          path: composeApp/build/compose/binaries/**/app/*/